version: 1
formatters:
  colorlog:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s"
handlers:
  console:
    class: colorlog.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]