defaults:
  - _self_
  - paths: default.yaml
  - data: dog_breed.yaml
  - model: dog_classifier.yaml
  - trainer: default.yaml

task_name: "evaluate"

seed: 42

# Checkpoint path resolver
ckpt_path:
  _target_: src.utils.checkpoint_utils.find_latest_checkpoint
  dir: ${paths.log_dir}/runs

# Print the config tree using Rich
print_config: True

# Disable python warnings if they annoy you
ignore_warnings: True

# Check if debug mode is on
debug: False
